### ISSUE TITLE
Animated Gif Demo?

### ISSUE THREAD

**Issue by geirman** [hamidhadi/react-native-stretchy#1]
The component sounds interesting, and I think I can imagine what it does... but it would be nice if you added an animated GIF so that we could see it before installing it.

**Comment by hamidhadi** [comment]
@geirman Thank you for your suggestion. I will add it ASAP 😉

**Comment by geirman** [comment]
Cool, please let me know when it's up

**Comment by hamidhadi** [comment]
@geirman Now the demo is up 😉
