### ISSUE TITLE
Accessing the ref in order to run scroll operations on lists

### ISSUE THREAD

**Issue by xavierh81** [hamidhadi/react-native-stretchy#18]
Hi !
I'm using this library since few months and everything was great so far.
I have tried to add a "scrollTo" usage on the scrollView but I got the "classic" errors related to refs.

` Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()`

```
<StretchyScrollView
      ref={(ref) => this.productsSectionList = ref}
>
  ....
```

How should I process to do such thing ?

Thanks !

**Comment by hamidhadi** [comment]
Hey @xavierh81 👋 
Thanks for opening this issue and sorry for the late response.
You can now pass ref object in v4.

**Comment by xavierh81** [comment]
Hi @hamidhadi. I have tried to use the `ref` after upgrading the library to version 4.0.
But I still can't access to scroll methods. 
I got the "classic error": "this.productsSectionList.scrollTo is not a function"

Do you have any idea on how I can access to `scrollTo` and `scrollToLocation` methods of the StretchySectionList?

**Comment by xavierh81** [comment]
Actually, I just found the answer here: https://stackoverflow.com/questions/54617702/scrolltolocation-is-undefined-in-sectionlist-ref-of-react-native-neither-in-fla#comment96286933_54711573

As it's an Animated component, we have to use the `getNode()` function in order to use the SectionList functions.
