### ISSUE TITLE
support android ?

### ISSUE THREAD

**Issue by KingAmo** [hamidhadi/react-native-stretchy#27]
any plan ?

**Comment by hamidhadi** [comment]
Android doesn't have the same behaviour as iOS for over scrolling but you can still use RNStretchy on Android.

**Comment by KingAmo** [comment]
maybe we can use [react-native-gesture-handle](https://github.com/software-mansion/react-native-gesture-handler) in Android to implement this feature?

**Comment by hamidhadi** [comment]
@KingAmo It's possible to have a workaround for that. There are some native solutions on Github as well but, I wanted to keep this project as pure as possible with minimum dependencies. Having said it's not part of Android design patterns so I didn't prioritise that. 
If you think it's worth having and have an idea to implement it, please feel free to open a PR. We can probably make it an optional flag. + RNGesture handler is part of almost all RN projects these days so it shouldn't be a problem. 🤔
