### ISSUE TITLE
Image component cannot have child in react 50

### ISSUE THREAD

**Issue by denny64** [hamidhadi/react-native-stretchy#3]
How to fix this?

**Comment by hamidhadi** [comment]
Thank you @denny64 
You are right but I have another issue with the new version of `react-native-linear-gradient`.
I just opened an [issue](https://github.com/react-native-community/react-native-linear-gradient/issues/249) for that and waiting for a solution to fix.
After that, I will publish new update.

**Comment by denny64** [comment]
@hamidhadi Thanks

**Comment by hamidhadi** [comment]
@denny64 I just published `1.0.0`. Please upgrade your dependency.
I close this issue but If you have any problem feel free to reopen this and let me know about your problem.
