### ISSUE TITLE
BVLinearGradient

### ISSUE THREAD

**Issue by olivinesguerra** [hamidhadi/react-native-stretchy#8]
how do use this library using Expo. Thanks

**Comment by GustavoDinizMonteiro** [comment]
Any updates about this ?

**Comment by hamidhadi** [comment]
Hey guys 👋 
I'm working on the next version of this package.
Sorry for the delay and I'm trying to do my best to deliver that asap.
I'll leave this issue open until the new release.

**Comment by burhanahmed92** [comment]
Kindly add expo support

**Comment by olivinesguerra** [comment]
Thanks

**Comment by hamidhadi** [comment]
Hey guys 👋 
Now you can use this package via expo as well.
Check [this PR](https://github.com/hamidhadi/react-native-stretchy/pull/24) 🙂
